### ISSUE TITLE
Memory allocation failures in "cargo test"

### ISSUE THREAD

**Issue by penberg** [DataDog/scipio#1]
````
[penberg@nero scipio]$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/scipio-77adf7d6245cfb16

running 14 tests
test executor::create_fail_to_bind ... ok
test executor::create_and_destroy_executor ... ok
test executor::invalid_task_queue ... ok
test executor::create_and_bind ... ok
test executor::spawn_without_executor ... ok
test local_semaphore::broken_semaphore_if_close_happens_first ... ok
test executor::task_optimized_for_throughput ... FAILED
test local_semaphore::explicit_signal_unblocks_waiting_semaphore ... FAILED
test executor::ten_yielding_queues ... FAILED
test local_semaphore::broken_semaphore_returns_the_right_error ... FAILED
test local_semaphore::permit_raii_works ... FAILED
test local_semaphore::semaphore_acquisition_for_zero_unit_works ... FAILED
test local_semaphore::broken_semaphore_if_acquire_happens_first ... ok
test executor::task_with_latency_requirements ... ok

failures:

---- executor::task_optimized_for_throughput stdout ----
thread 'executor::task_optimized_for_throughput' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/parking.rs:359:19

---- local_semaphore::explicit_signal_unblocks_waiting_semaphore stdout ----
thread 'local_semaphore::explicit_signal_unblocks_waiting_semaphore' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/parking.rs:359:19

---- executor::ten_yielding_queues stdout ----
thread 'executor::ten_yielding_queues' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/parking.rs:359:19

---- local_semaphore::broken_semaphore_returns_the_right_error stdout ----
thread 'local_semaphore::broken_semaphore_returns_the_right_error' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/parking.rs:359:19

---- local_semaphore::permit_raii_works stdout ----
thread 'local_semaphore::permit_raii_works' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/parking.rs:359:19

---- local_semaphore::semaphore_acquisition_for_zero_unit_works stdout ----
thread 'local_semaphore::semaphore_acquisition_for_zero_unit_works' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/parking.rs:359:19


failures:
    executor::task_optimized_for_throughput
    executor::ten_yielding_queues
    local_semaphore::broken_semaphore_returns_the_right_error
    local_semaphore::explicit_signal_unblocks_waiting_semaphore
    local_semaphore::permit_raii_works
    local_semaphore::semaphore_acquisition_for_zero_unit_works

test result: FAILED. 8 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by penberg** [comment]
Perhaps my kernel is too old?

```
[penberg@nero scipio]$ uname -a
Linux nero 5.7.12-200.fc32.x86_64 #1 SMP Sat Aug 1 16:13:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by penberg** [comment]
Hmm, probably not, some of the `io_uring_setup` calls succeed. The failing ones look like this (there's a concurrent `io_uring_setup` that succeeds):

```
454861 io_uring_setup(128, {flags=0, sq_thread_cpu=0, sq_thread_idle=0 <unfinished ...>
454867 sigaltstack(NULL,  <unfinished ...>
454859 <... io_uring_setup resumed>, sq_entries=128, cq_entries=256, features=IORING_FEAT_SINGLE_MMAP|IORING_FEAT_NODROP|IORING_FEAT_SUBMIT_STABLE|IORING_FEAT_RW_CUR_POS|IORING_FEAT_CUR_PERSONALITY|IORING_FEAT_FAST_POLL, sq_off={head=0, tail=64, ring_mask=256, ring_entries=264, flags=276, dropped=272, array=4928}, cq_off={head=128, tail=192, ring_mask=260, ring_entries=268, overflow=280, cqes=320, flags=0}}) = 5
454862 getrandom( <unfinished ...>
454861 <... io_uring_setup resumed>})   = -1 ENOMEM (Cannot allocate memory)
```

Let me know if you want the full strace log.

**Comment by L1AN0** [comment]
Same error here.

```
uname -a
Linux nozomizilla 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux
```

**Comment by penberg** [comment]
@glommer If everyone is going to hit this with default `memlock` rlimit, then it's best to fix the code to use less of it. However, there's no harm in also improving the error message, which I did in pull request #4.

**Comment by glommer** [comment]
@penberg I agree it is better but it may not be possible in practice because we can't control how many threads will be spawned: at some point it may blow up the memory.

However let's not allow perfect to be the enemy of the good here: I agree with you that at least for the common case of running a bunch of tests it shouldn't fail.

I'll figure something out next.

May I ask how many threads your tests were spawning and what were your mlock limit ?

**Comment by penberg** [comment]
The default `memlock` limit on Fedora 32 is 64 KB. I am counting 71 `clone` calls with `CLONE_VM` for the `task_optimized_for_throughput` test case, for example. I needed to bump the `memlock` rlimit to 512 KiB to make it run.
